[workspace]

members = [
    "geometry",
    "application",
    "patternmatching",
    "iterators",
    "errorhandling",
    "macros",
    "multithreading",
    "hdfarray",
    "arrays",
    "serialization"
]